[pytest]
python_files=ls_test_*.py test_*.py  # 识别 ls_test_开头的文件
python_classes =*Test*               # 识别类名含Test的类
python_functions =ls_test_* test_*   # 识别 ls_test_开头的方法

addopts=-vs --alluredir=./reports/temp

# 强制指定用例目录，避免找错
testpaths=./test_case